name: deploy on push
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4 
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: 47.94.57.95
          username: ubuntu
          port: 22
          key: -----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEAyRP7220S+G3hB7MMKUqI2Xh1phSrKx0Bd08A4Zql2HwrrMtwnv7CotQgShsiAraipna+Aq8hDV/XFjVuAC+nFIjMi+7hBgs6mVTWHoN34hKeZvKK0SHsonp0IYkJkYJrFIzVkIGwIMCCb5wq4Zd0KX1weLvT8AWCNgnVgIELbzTW1AYxIEFsBtoGykw7OlgRyx6h3ioLDW+asqFa0++YTsEFGbYwaddgXVGs3YAKsnmRIfHGmnnlzM1YJ8zEx7XnsouUUXIWs2E2T/rBv7NGzEkOB3PHntOK1J8CKuQg3b1LUFpMe/Fr86seqTxECT0Gt9/+KZ702nYHOy5zXhVFLQIDAQABAoIBAGdkESKYiSKYTRcKZ3xryMYZfFTzV7gJaBGS298lB5Wy8zocOUJnuGjFLf0symYexq9VawoyRop79zqCKpeJ6R1T4ekp4Saca3sf9iEmdGQYMr64g8xY5zX8RO5hajwZlTmx2LY/GPMeSXNeF2Z728zhpQ1PdwB5tKRYliFHOTvqQxtGiKurOHKWn8Aq+BwXEtKYLODucNcCku4ECHwo0JD1Sc8RFxdieE6GczPclNPCUHuu2vx42kyfjQrIjuWy+SCTY3kW4I9CqDyAx0OWu23orv0nm+gbeziRAl/X3AYPo74ShFYk7aohqY25n8lDMSoxmjp2fQsNfS44EY4o3PkCgYEA+SsNsFjEQPk3fW4qQlm4IDQIYiIXjykhaD9Jajw0bGHCZMv6aCIpP7B/KGtljGt8chYGEuChdLfBQf7t7hXUL6RlnWKWrXiSRegqvfD7lJQC7cQdiFQ6Irh5dhOHb4wRV8UcmvzteFCxUGpunt5oHDt2O4vWEMxWvvTm6Ofp7BcCgYEAzpdhCWKOt1LdZQpuJtSgvfbYgWTN5qXB0ntvOmMuYWja/a6SZK5g1tdIf8djSAxRIDds721sBzsrZ0q5qXIhLVboSuutzU9i/bi9+0vSu73PqyKqbYsd3wQfoTRCRYzWvQ+rAm2rcwsqJ5bjTM8J5LeOgsGi+I4YabfftVJPD1sCgYBAAXpDuZm4YwyJEPqUDr4Ir7UTmFRa9yLYx6ERRCPnT3mDMQ7DHztfW/ReKrBsUNQn7lZjFQcEl4tya40tIrheAKoFsuSn7RgOEySfpD7MHPVfpIg9k/1XG/I/jaa11dJCrKS7f4t0462Yza5a6yDtV6z4gORdblA+P2TtoV1qwwKBgEVQy1EfzWy7E+eD8WN78hbqzMfVb7RUp0yc97vqbTRnvxpgyWOYkotjHkMpPil9YHbjwdwvpZBjjPOSQesVjQYuY7BHlUAOw9MHek7nqOQvEo+ECRTKGZKrSoWHCDlXwPEcYa9l5qGp/FHeMZOi39nqsJk0qR6mZpCKDjhDTp2DAoGBAKHcQo303PAZ3aIE8WBfgkUu8BEYaHlBwc8xBYz88qyjUyrUSLnNvPtrqwBCbEdD+Txze4ufjlo79yDMQG3wdIw9NsGp/q0oA540+4GGdFs4Ax1ZOTHnJUMG0l4kd/lY+4Hj3SOv4JCYcU+6TL0jGxkZLCnRs8u+0CVWRT7W56iU-----END RSA PRIVATE KEY-----

          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1