name: deploy on push production branch
on:
  push:
    branches:
      - prod

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4

      - name: Prepare SSH folder
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add production server to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: set ubuntu as the owner of /var/www/html (Ubuntu 24+)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            sudo chown -R ubuntu /var/www/html

      - name: copy file to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1

      - name: set root as the owner of /var/www/html (Ubuntu 24+)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            sudo chown -R root /var/www/html