name: deploy on push
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Copy files to server
        uses: appleboy/scp-action@master
        - name: Download drone-scp
  run: |
    for i in {1..5}; do
      wget -q https://github.com/appleboy/drone-scp/releases/download/v1.8.0/drone-scp-1.8.0-linux-amd64 -O /usr/local/bin/drone-scp && break || sleep 5;
    done
    chmod +x /usr/local/bin/drone-scp
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1
          timeout: 30s
          command_timeout: 10m
          protocol: tcp